version: '2'
services:
  web:
    image: secrect/odoo12:latest
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web:/var/lib/odoo
      - odoo-config:/etc/odoo
      - odoo-addons:/mnt/extra-addons
      - odoo-package:/usr/lib/python3/
  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db:/var/lib/postgresql/data/pgdata
volumes:
  odoo-web:
  odoo-config:
  odoo-package:
  odoo-addons:
  odoo-db:
